---

- name: Install nginx
  become: yes
  apt: 
    name: nginx 
    state: present

- name: Copy nginx configuration for flask
  become: yes
  template: 
    src: default.conf 
    dest: /etc/nginx/conf.d/default.conf

- name: Copy nginx configuration to nginx site-available
  become: yes
  template: 
    src: default.conf 
    dest: /etc/nginx/sites-available/default.conf

- name: Copy nginx configuration to sites-enabled
  become: yes
  template: 
    src: default.conf 
    dest: /etc/nginx/sites-enabled/default.conf
    
- name: Ensure that the default site-available is removed
  file: path=/etc/nginx/site-available/default state=absent

- name: Ensure that the default site-enabled  is removed
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: restart nginx
  become: yes
  service: name=nginx state=restarted enabled=yes
