---

- name: install PHP  
  become: yes
  apt: pkg={{item}} state=present 
  with_items:
    - php5.6
    - php5.6-mbstring 
    - php5.6-mcrypt 
    - php5.6-mysql 
    - php5.6-xml
    - php56-php-ldap